version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: last-mile-db
    restart: always
    environment:
      POSTGRES_USER: user_logistics
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: last_mile_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: